import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'], // You can specify subsets as needed
  variable: '--font-inter', // Optional: To create a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>{children}</body>
    </html>
    
  );
}
